"""add region table

Revision ID: 7c53011d1fb2
Revises:
Create Date: 2023-01-14 14:12:59.336633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c53011d1fb2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "region",
        sa.Column("region_id", sa.SmallInteger(), nullable=False),
        sa.Column("region_description", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("region_id", name=op.f("pk_region")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("region")
    # ### end Alembic commands ###
